was added requirements.txt #5
qaivanpleten/repspark_ios_tests pull request #11
Opened 2017-08-16 10:21 UTC by qaivanpleten

there are only 4 packages, which I use. I will update requirements file

2017-08-16 13:58 UTC, extsoft requested changes
@qaivanpleten please add all used packages to requirements file (the packages were installed with `pip install`).

2017-08-16 15:15 UTC, qaivanpleten commented
@extsoft 
I added all packages which I use. All which I remember)

2017-08-16 15:31 UTC, extsoft commented
> @extsoft
I added all packages which I use. All which I remember)

@qaivanpleten 
The file is empty in PR - https://github.com/qaivanpleten/repspark_ios_tests/pull/11/files.

2017-08-16 15:32 UTC, extsoft commented
And use `pip freeze` to check the packages.

2017-08-16 15:51 UTC, qaivanpleten commented
вроде пофиксил, сделал коммит и пуш реквест с фиксами. чекни плиз

2017-08-18 09:20 UTC, extsoft requested changes

2017-08-18 09:20 UTC, extsoft commented on requirements.txt
> +altgraph==0.10.2
There are a lot of transitive dependencies in this file. You need only top level dependencies. To get them, please install `pip install pipdeptree` and run `pipdeptree`. You will see the output like 
```bash
pipdeptree==0.10.1 # skip this and its tree as pipdeptree is a debug tool 
  - pip [required: >=6.0.0, installed: 7.1.2] 
pytest==3.2.0 # add to requirements.txt
  - py [required: >=1.4.33, installed: 1.4.34] # transitive = skip
  - setuptools [required: Any, installed: 18.2] # transitive = skip
selenium==3.4.3 # add to requirements.txt
```

@qaivanpleten, please leave only main dependencies.

2017-08-18 13:13 UTC, qaivanpleten commented
сделал. стало меньше. но все равно 43 пакета. хз какие из них нужны. предлагаю обсудить лично

2017-08-19 21:40 UTC, extsoft commented
@qaivanpleten 
> сделал. стало меньше. но все равно 43 пакета. хз какие из них нужны. предлагаю обсудить лично

Try to use [pipreqs](https://github.com/bndr/pipreqs).

2017-08-22 07:22 UTC, qaivanpleten commented
@extsoft 
I believe now there are only used packages

2017-08-28 09:31 UTC, extsoft approved these changes
Great job!

2017-08-28 09:31 UTC, merged