Reduce code duplication #6
qaivanpleten/repspark_ios_tests pull request #12
Opened 2017-08-16 14:44 UTC by qaivanpleten

Я не решил задачу пока. Нужна помощь. 
Добавил файл setup_class.py, в нем собираюсь хранить функции setUpClass и tearDownClass
1. Не понятно, как объявить класс в котором будут функции setUpClass и tearDownClass
2. Не уверен что я правильно объявляю функции setUpClass и tearDownClass
3. Какие параметры должны принимать функции setUpClass и tearDownClass? 
4. Что должны возвращать функции setUpClass и tearDownClass
5. И наконец. Как мне вызывать функции setUpClass и tearDownClass непосредственно в тестах?

2017-08-18 09:01 UTC, extsoft requested changes
@qaivanpleten hope my comments will answer all your questions. If no, please ask them again.

2017-08-18 09:01 UTC, extsoft commented on repspark_at/actions/setup_class.py
> +    #@classmethod  I'm not sure if I should use classmethod here
[Here](https://docs.python.org/3/library/unittest.html#unittest.TestCase.setUpClass) is the answer.

2017-08-18 09:01 UTC, extsoft commented on repspark_at/actions/setup_class.py
> +        return '???????????'
`return` statement is not required.

2017-08-18 09:01 UTC, extsoft commented on repspark_at/actions/setup_class.py
> +class setUpClass('???????????????'):
Please take a look at the following example. Hope, it'll clarify the task for you.
```python
import unittest


class Test(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.foo = 'foo'
        print("set class: {f}".format(f=cls.foo))

    @classmethod
    def tearDownClass(cls):
        cls.foo = None
        print("destroy class: {f}".format(f=cls.foo))


class Test1(Test):
    def test_1(self):
        print('{f}: test 1'.format(f=self.foo))

    def test_2(self):
        print('{f}: test 2'.format(f=self.foo))


if __name__ == '__main__':
    unittest.main()
```

2017-08-18 09:01 UTC, extsoft commented on requirements.txt
> +.ignore==1.7.6
@qaivanpleten please remove this file from this branch. This is a separate task and it has to be implemented in the separate branch.

2017-08-21 15:02 UTC, qaivanpleten commented
1. SetUpClass поменял во всех тестах. Привел все к нормальному виду
2. Переименовал все классы использую camelback
3. Реформатировал все файлы

2017-08-28 09:35 UTC, extsoft requested changes
@qaivanpleten please resolve conflicts with the master branch.

2017-08-28 15:57 UTC, extsoft approved these changes

2017-08-28 15:58 UTC, merged